import { Lora } from "next/font/google"
import "./globals.css"

const lora = Lora({ subsets: ["latin"] })

export const metadata = {
  title: '"Drizzle" & "Sizzle" Olive Oil | Graza',
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>{children}</body>
    </html>
  )
}
